title: Oh Hello Ana
name: Oh Hello Ana - Ana Rodrigues blog
email: contact@ohhelloana.blog
description: Ana's personal blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ohhelloana.blog" # the base hostname & protocol for your site, e.g. http://example.com
author: Ana R
github_source: "https://github.com/ohhelloana/ohhelloana.blog"
twitter_username: ohhelloana
github_username:  ohhelloana

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-webmention_io
exclude:
  - Gemfile
  - Gemfile.lock

permalink: /:title

sass:
  sass_dir: _sass
  style: compressed

webmentions:
  # Enter your webmention.io username
  username: ohhelloana.blog
  cache_bad_uris_for: 5
  # If you've changed domain in the past, list the old ones here
  legacy_domains:
    - http://ohhelloana.blog
    - http://www.ohhelloana.blog
  # I have the JavaScript portion of the plugin disabled, since I'm
  # triggering builds with Netlify
  js: false